from . import account_invoice
from . import product_product
from . import res_partner
from . import res_partner_contract
from . import res_partner_contract_annex
from . import res_partner_contract_field
from . import res_partner_contract_field_transient
from . import res_partner_document_template
from . import sale_order
